FROM node:alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . ./
RUN find src -regex '.*\.jsx?' -exec sed -i 's~http://127.0.0.1:8000/~https://mpr.zarybnicky.com/api/~g' {} \;
RUN npm run build

# production env
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN sed -i 's/80;/3000;/g' /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
