version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - '.:/app'
