version: '3.7'

services:
  web:
    build:
      context: ./mpr
      dockerfile: ./Dockerfile
    container_name: mpr_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mpr:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./mpr/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./mpr/.env
    ports:
      - 5432:5432

volumes:
  postgres_data:
