version: '3.7'
services:
  react-ui:
    build:
      context: ./mpr/react
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - '.:/app'
