# Generated by Django 3.1.7 on 2021-03-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ico',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
