# Generated by Django 3.2 on 2021-04-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210416_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='update_user',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
