# Generated by Django 3.2 on 2021-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210406_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contract_number',
            field=models.CharField(max_length=50),
        ),
    ]
