Company:
  title: Company
  type: object
  properties:
    ico:
      format: string
      example: '2616685'
    name:
      type: string
      example: 'test'
    phone_number:
      type: string
      example: '+420234694111'
    ad_volume:
      type: int
      example: 100
    status:
      type: string
      example: 'volna'
    contact_adress:
      type: object
      properties:
        id:
          format: int
          example: 1
        street:
          type: string
          example: 'Radlická 3294/10'
        zip_code:
          type: string
          example: '15000'
        city:
          type: string
          example: 'Praha'
        country:
          type: string
          example: 'Czech Republic'
    billing_adress:
      type: object
      properties:
        id:
          format: int
          example: 2
        street:
          type: string
          example: 'Radlická 3294/10'
        zip_code:
          type: string
          example: '15000'
        city:
          type: string
          example: 'Praha'
        country:
          type: string
          example: 'Czech Republic'

Contact:
  title: Contact
  type: object
  properties:
    id:
      format: int
      example: 1
    name:
      type: string
      example: 'test'
    surname:
      type: string
      example: 'test'
    phone:
      type: string
      example: "+420212345678"
    email:
      type: string
      example: 'test@mpr.io'
    company:
      type: object
      properties:
        ico:
          format: string
          example: '2616685'
        name:
          type: string
          example: 'test'


PostContact:
  title: Contact
  type: object
  properties:
    id:
      format: int
      example: 1
    name:
      type: string
      example: 'test'
    surname:
      type: string
      example: 'test'
    phone:
      type: string
      example: "+420212345678"
    email:
      type: string
      example: 'test@mpr.io'
    company:
      type: string
      example: '2616685'

Event:
  title: Event
  type: object
  properties:
    id:
      format: int
      example: 1
    name:
      type: string
      example: 'test'
    date:
      type: date
      example: "2021-04-03"
    time:
      type: time
      example: "15:00:00"
    description:
      type: string
      example: "Tea with client"
    company:
      type: string
      example: '2616685'
    reminder:
      type: bool
      example: false

PostEvent:
  title: Event
  type: object
  properties:
    id:
      format: int
      example: 1
    name:
      type: string
      example: "test"
    date:
      type: date
      example: "2021-04-05"
    time:
      type: time
      example: "15:00:00"
    description:
      type: string
      example: "Tea with client"
    company:
      type: string
      example: '2616685'
    reminder:
      type: bool
      example: true

Order:
  title: Order
  type: object
  properties:
    id:
      format: int
      example: 1
    date:
      type: date
      example: "2021-04-03"
    contract_number:
      type: int
      example: 2341
    sum:
      type: int
      example: 300
    company:
      type: string
      example: '2616685'