openapi: 3.0.2

info:
  description: |
    MPR school project
  version: "1.0.0"
  title: MPR project

tags:
  - name: company
    x-displayName: Company
    description: >
      Resources for working with company.
  - name: contact
    x-displayName: Contact
    description: >
      Resources for working with contact.
  - name: event
    x-displayName: Event
    description: >
      Resources for working with event.
  - name: order
    x-displayName: Order
    description: >
        Resources for working with order.
  - name: user
    x-displayName: User
    description: >
        Resources for working with user.


paths:
  /company:
    $ref: './company.yml'
  /company/{id}:
    $ref: './company_id.yml'
  /contact:
    $ref: './contact.yml'
  /contact/{id}:
    $ref: './contact_id.yml'
  /event:
    $ref: './event.yml'
  /event/{id}:
    $ref: './event_id.yml'
  /order:
    $ref: './order.yml'
  /order/{id}:
    $ref: './order_id.yml'
  /user:
    $ref: './user.yml'
