name: Deploy to 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          remote_path: /root/mpr
          remote_host: 157.90.24.140
          remote_user: root
          remote_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}

      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: root@157.90.24.140
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /root/mpr
          stack_file_name: docker-compose.yml
          keep_files: 5
          args: up -d --build
          docker_prune: 'false'
          pull_images_first: 'false'
