name: Deploy to 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "."
          REMOTE_HOST: 157.90.24.140
          REMOTE_USER: root
          TARGET: /root/mpr

      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: root@157.90.24.140
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /root/mpr
          stack_file_name: docker-compose.yml
          keep_files: 5
          args: up -d
          docker_prune: 'false'
          pull_images_first: 'false'
