name: Build & deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-frontend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend
          tags: zarybnicky/mpr-frontend:latest
          push: true

  build-backend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          tags: zarybnicky/mpr-backend:latest
          push: true

  deploy:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: RSync to prod
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          remote_path: /root/mpr
          remote_host: 157.90.24.140
          remote_user: root
          remote_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}

      - name: Docker-compose on prod
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: root@157.90.24.140
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /root/mpr
          stack_file_name: docker-compose.prod.yml
          keep_files: 5
          args: up -d
          docker_prune: 'true'
          pull_images_first: 'true'
