# Generated by Django 3.2 on 2021-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sum', models.PositiveIntegerField()),
            ],
            options={
                'default_related_name': 'Invoice',
            },
        ),
    ]
